freelancer:
    resource: "@FreelancerBundle/Resources/config/routing.yml"
    prefix:   /

jobowner:
    resource: "@JobownerBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:     
    resource: "@FOSUserBundle/Resources/config/routing/all.xml" 
    

