MyApp\FreelancerBundle\Entity\Projets:
    type: entity
    table: projets
    id:
        projetId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            column: projet_id
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        description:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        categorie:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        nombreFreelancer:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: nombre_freelancer
        level:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        typecontrat:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
            column: typeContrat
        salaire:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 10
        duree:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        etat:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        username:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }
