MyApp\JobownerBundle\Entity\Projetv:
    type: entity
    table: projetv
    repositoryClass: MyApp\JobownerBundle\Entity\ProjetvRepository
    id:
        Id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        freelancer:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        jobowner:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        projetId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: projetid
    lifecycleCallbacks: {  }
