MyApp\FreelancerBundle\Entity\Utilisateurs:
    type: entity
    table: utilisateurs
    uniqueConstraints:
        UNIQ_497B315E92FC23A8:
            columns:
                - username_canonical
        UNIQ_497B315EA0D96FBF:
            columns:
                - email_canonical
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        prenom:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        age:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        sexe:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        adresse:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        email:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        password:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        type:
            type: string
            scale: 0
            length: 20
            unique: false
            nullable: true
            precision: 0
        cv:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        username:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        usernameCanonical:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: username_canonical
        emailCanonical:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: email_canonical
        enabled:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        salt:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        lastLogin:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: last_login
        locked:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        expired:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        expiresAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: expires_at
        confirmationToken:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: password_requested_at
        roles:
            type: array
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        credentialsExpired:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: credentials_expire_at
        montant:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        photoprofil:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }
