MyApp\FreelancerBundle\Entity\Projetv:
    type: entity
    table: projetv
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        freelancer:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        jobowner:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        projetid:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }
