MyApp\JobownerBundle\Entity\Utilisateurs:
    type: entity
    table: utilisateurs
    repositoryClass: MyApp\JobownerBundle\Entity\UtilisateursRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        prenom:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        age:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        sexe:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        adresse:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        type:
            type: string
            scale: 0
            length: 20
            unique: false
            nullable: true
            precision: 0
        photoprofil:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        cv:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        montant:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }
