feedbacks:
    path:     /
    defaults: { _controller: "FreelancerBundle:Feedbacks:index" }

feedbacks_show:
    path:     /{id}/show
    defaults: { _controller: "FreelancerBundle:Feedbacks:show" }

feedbacks_new:
    path:     /new
    defaults: { _controller: "FreelancerBundle:Feedbacks:new" }

feedbacks_create:
    path:     /create
    defaults: { _controller: "FreelancerBundle:Feedbacks:create" }
    methods:  POST

feedbacks_edit:
    path:     /{id}/edit
    defaults: { _controller: "FreelancerBundle:Feedbacks:edit" }

feedbacks_update:
    path:     /{id}/update
    defaults: { _controller: "FreelancerBundle:Feedbacks:update" }
    methods:  [POST, PUT]

feedbacks_delete:
    path:     /{id}/delete
    defaults: { _controller: "FreelancerBundle:Feedbacks:delete" }
    methods:  [POST, DELETE]
